/**
 * API Error codes
 * @description Standardized error codes for API responses
 */
export const ERROR_CODES = {
    // General errors (1xxx)
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    BAD_REQUEST: 'BAD_REQUEST',
    CONFLICT: 'CONFLICT',

    // Authentication errors (2xxx)
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_INVALID: 'TOKEN_INVALID',
    CREDENTIALS_INVALID: 'CREDENTIALS_INVALID',

    // User errors (3xxx)
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
    ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',

    // Subscription errors (4xxx)
    SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
    SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
    SUBSCRIPTION_LIMIT_REACHED: 'SUBSCRIPTION_LIMIT_REACHED',
    PAYMENT_FAILED: 'PAYMENT_FAILED',

    // Integration errors (5xxx)
    INTEGRATION_NOT_FOUND: 'INTEGRATION_NOT_FOUND',
    INTEGRATION_DISABLED: 'INTEGRATION_DISABLED',
    SCRAPING_FAILED: 'SCRAPING_FAILED',
    RATE_LIMITED: 'RATE_LIMITED',

    // AI errors (6xxx)
    AI_SERVICE_UNAVAILABLE: 'AI_SERVICE_UNAVAILABLE',
    AI_QUOTA_EXCEEDED: 'AI_QUOTA_EXCEEDED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * HTTP Status code mapping for error codes
 */
export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
    [ERROR_CODES.INTERNAL_ERROR]: 500,
    [ERROR_CODES.VALIDATION_ERROR]: 400,
    [ERROR_CODES.NOT_FOUND]: 404,
    [ERROR_CODES.BAD_REQUEST]: 400,
    [ERROR_CODES.CONFLICT]: 409,
    [ERROR_CODES.UNAUTHORIZED]: 401,
    [ERROR_CODES.FORBIDDEN]: 403,
    [ERROR_CODES.TOKEN_EXPIRED]: 401,
    [ERROR_CODES.TOKEN_INVALID]: 401,
    [ERROR_CODES.CREDENTIALS_INVALID]: 401,
    [ERROR_CODES.USER_NOT_FOUND]: 404,
    [ERROR_CODES.USER_ALREADY_EXISTS]: 409,
    [ERROR_CODES.EMAIL_NOT_VERIFIED]: 403,
    [ERROR_CODES.ACCOUNT_DISABLED]: 403,
    [ERROR_CODES.SUBSCRIPTION_REQUIRED]: 402,
    [ERROR_CODES.SUBSCRIPTION_EXPIRED]: 402,
    [ERROR_CODES.SUBSCRIPTION_LIMIT_REACHED]: 402,
    [ERROR_CODES.PAYMENT_FAILED]: 402,
    [ERROR_CODES.INTEGRATION_NOT_FOUND]: 404,
    [ERROR_CODES.INTEGRATION_DISABLED]: 400,
    [ERROR_CODES.SCRAPING_FAILED]: 502,
    [ERROR_CODES.RATE_LIMITED]: 429,
    [ERROR_CODES.AI_SERVICE_UNAVAILABLE]: 503,
    [ERROR_CODES.AI_QUOTA_EXCEEDED]: 429,
} as const;
